project_name: adguard-exporter
release:
  github:
    owner: znand-dev
    name: adguardexportergo

builds:
  - id: adguard-exporter
    main: ./main.go
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64, arm]
    goarm: [6]
    ldflags:
      - -s -w
    binary: adguard-exporter

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - adguard-exporter
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
