project_name: adguardexporter

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    main: main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm

archives:
  - format: tar.gz

checksum:
  name_template: 'checksums.txt'

dockers:
  - goos: linux
    goarch: amd64
    context: .
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/znand-dev/adguardexporter:{{ .Tag }}-amd64
      - ghcr.io/znand-dev/adguardexporter:latest-amd64

  - goos: linux
    goarch: arm64
    context: .
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/znand-dev/adguardexporter:{{ .Tag }}-arm64v8
      - ghcr.io/znand-dev/adguardexporter:latest-arm64v8

  - goos: linux
    goarch: arm
    context: .
    build_flag_templates:
      - "--platform=linux/arm/v7"
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/znand-dev/adguardexporter:{{ .Tag }}-armv7
      - ghcr.io/znand-dev/adguardexporter:latest-armv7

  - goos: linux
    goarch: arm
    context: .
    build_flag_templates:
      - "--platform=linux/arm/v6"
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/znand-dev/adguardexporter:{{ .Tag }}-armv6
      - ghcr.io/znand-dev/adguardexporter:latest-armv6

docker_manifests:
  - name_template: ghcr.io/znand-dev/adguardexporter:{{ .Tag }}
    image_templates:
      - ghcr.io/znand-dev/adguardexporter:{{ .Tag }}-amd64
      - ghcr.io/znand-dev/adguardexporter:{{ .Tag }}-arm64v8
      - ghcr.io/znand-dev/adguardexporter:{{ .Tag }}-armv7
      - ghcr.io/znand-dev/adguardexporter:{{ .Tag }}-armv6

  - name_template: ghcr.io/znand-dev/adguardexporter:latest
    image_templates:
      - ghcr.io/znand-dev/adguardexporter:latest-amd64
      - ghcr.io/znand-dev/adguardexporter:latest-arm64v8
      - ghcr.io/znand-dev/adguardexporter:latest-armv7
      - ghcr.io/znand-dev/adguardexporter:latest-armv6
