version: 1

project_name: adguard-exporter

builds:
  - main: ./main.go
    binary: adguard-exporter
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: znand-dev
    name: adguardexporter

dockers:
  - image_templates:
      - ghcr.io/znand-dev/adguard-exporter:{{ .Version }}
      - ghcr.io/znand-dev/adguard-exporter:latest
    dockerfile: Dockerfile
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    use: buildx
