{
 "title": "AdGuard Metrics Statistics",
 "tags": [
  "DNS",
  "AdGuard",
  "Server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "AdGuard Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "🛡Protection & Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_protection_enabled", "legendFormat": "Protection Status" },
    { "expr": "adguard_running", "legendFormat": "Service Status" }
   ]
  },
  {
   "title": "🔌Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Rate (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(adguard_blocked_filtering_total / adguard_dns_queries_total) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Processing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_avg_processing_time * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚡ 📈 Total DNS Query Rate",
   "type": "timeseries",
   "description": "\nThis panel displays the **real-time DNS query rate per second**, calculated over the last 1 minute.\n\n- Based on the metric: `adguard_dns_queries_total`\n- Uses the Prometheus `rate()` function:\n\n",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(adguard_dns_queries_total[1m])",
     "legendFormat": "DNS QPS"
    }
   ]
  },
  {
   "title": "🔍 DNS Query Types",
   "type": "timeseries",
   "description": "This panel shows the **average number of DNS queries per second**, grouped by query type (A, AAAA, PTR, etc.).\n\n- Based on the metric: `adguard_query_type_total`\n- Uses the Prometheus `rate()` function with a 5-minute range:",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(adguard_query_type_total[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "🌐 Avg Upstream Response Time",
   "type": "timeseries",
   "description": "This panel displays the **average response time of DNS upstream servers**, in milliseconds.\n\n- Based on metric: `adguard_upstream_avg_response_time_seconds`\n- Converted to milliseconds by multiplying with 1000:",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "adguard_upstream_avg_response_time_seconds * 1000",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "📈 Query Blocks - Real-Time per Client/Reason",
   "type": "timeseries",
   "description": "This panel displays the **real-time DNS query block rate per second**, grouped by client IP and the reason why the query was blocked or allowed.\n\n- Based on metric: `adguard_query_client_reason_total`\n- Uses Prometheus query:",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "o/s" } },
   "targets": [
    {
     "expr": "sum(rate(adguard_query_client_reason_total[1m])) by (client, reason)",
     "legendFormat": "{{client}} - {{reason}}"
    }
   ]
  },
  {
   "title": "📡Top Clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "topk(10, sum(adguard_query_client_reason_total) by (client))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌍 Top Queried Domains",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "topk(10, adguard_query_domain_total)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "🚫 Block Reasons",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(adguard_query_reason_total) by (reason)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🚫 Top Blocked Domains",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "topk(10, adguard_top_blocked_domain_total)",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}